interface Destination2 {
  position?: [number, number];
  visited?: boolean;
  name?: string;
  poeng?: number;
  geom?: string;
  id: number;
  points: number;
  fk_telltur_konkurranse: number;
  turmal_id: number;
  turmal_type: string;
  turmal_navn: string;
  telltur_turmaal_id: string;
  _editable: boolean;
}

const turmal55Forforende: Destination2[] = [
  {
    id: 9555,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5239,
    turmal_type: "Fottur",
    turmal_navn: "Bjørntinden",
    telltur_turmaal_id: "myghxi9g_5239",
    _editable: false,
  },
  {
    id: 9556,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5229,
    turmal_type: "Fottur",
    turmal_navn: "Gjerøyfjellet",
    telltur_turmaal_id: "myghxi9g_5229",
    _editable: false,
  },
  {
    id: 9557,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5230,
    turmal_type: "Fottur",
    turmal_navn: "Breiviktinden",
    telltur_turmaal_id: "myghxi9g_5230",
    _editable: false,
  },
  {
    id: 9558,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5240,
    turmal_type: "Fottur",
    turmal_navn: "Rødøyløva",
    telltur_turmaal_id: "myghxi9g_5240",
    _editable: false,
  },
  {
    id: 9559,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5178,
    turmal_type: "Fottur",
    turmal_navn: "Sørlykta på Myken",
    telltur_turmaal_id: "myghxi9g_5178",
    _editable: false,
  },
  {
    id: 9560,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8018,
    turmal_type: "Fottur",
    turmal_navn: "Engenbreen",
    telltur_turmaal_id: "myghxi9g_8018",
    _editable: false,
  },
  {
    id: 9561,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 7713,
    turmal_type: "Fottur",
    turmal_navn: "Hornneset",
    telltur_turmaal_id: "myghxi9g_7713",
    _editable: false,
  },
  {
    id: 9562,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8019,
    turmal_type: "Fottur",
    turmal_navn: "Innerstøtt",
    telltur_turmaal_id: "myghxi9g_8019",
    _editable: false,
  },
  {
    id: 9563,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8008,
    turmal_type: "Fottur",
    turmal_navn: "Nedre Naver",
    telltur_turmaal_id: "myghxi9g_8008",
    _editable: false,
  },
  {
    id: 9564,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8011,
    turmal_type: "Fottur",
    turmal_navn: "Svartvasshamran",
    telltur_turmaal_id: "myghxi9g_8011",
    _editable: false,
  },
  {
    id: 9565,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 7924,
    turmal_type: "Fottur",
    turmal_navn: "Verdens Ende",
    telltur_turmaal_id: "myghxi9g_7924",
    _editable: false,
  },
  {
    id: 9566,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5303,
    turmal_type: "Fottur",
    turmal_navn: "Høgfjellknubben",
    telltur_turmaal_id: "myghxi9g_5303",
    _editable: false,
  },
  {
    id: 9567,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 7962,
    turmal_type: "Fottur",
    turmal_navn: "Jordbrua ved Fellvatnet",
    telltur_turmaal_id: "myghxi9g_7962",
    _editable: false,
  },
  {
    id: 9568,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5360,
    turmal_type: "Fottur",
    turmal_navn: "Sandhornet",
    telltur_turmaal_id: "myghxi9g_5360",
    _editable: false,
  },
  {
    id: 9569,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5372,
    turmal_type: "Fottur",
    turmal_navn: "Finnesfjellet",
    telltur_turmaal_id: "myghxi9g_5372",
    _editable: false,
  },
  {
    id: 9570,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8067,
    turmal_type: "Nærtur",
    turmal_navn: "Langsanden",
    telltur_turmaal_id: "gxaxz7hb_8067",
    _editable: false,
  },
  {
    id: 9571,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8078,
    turmal_type: "Fottur",
    turmal_navn: "Stabbursdalsryggen",
    telltur_turmaal_id: "myghxi9g_8078",
    _editable: false,
  },
  {
    id: 9572,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8081,
    turmal_type: "Nærtur",
    turmal_navn: "Elvestien ved Moldjordmoen",
    telltur_turmaal_id: "gxaxz7hb_8081",
    _editable: false,
  },
  {
    id: 9573,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8079,
    turmal_type: "Fottur",
    turmal_navn: "Kristinagammen",
    telltur_turmaal_id: "myghxi9g_8079",
    _editable: false,
  },
  {
    id: 9574,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8076,
    turmal_type: "Fottur",
    turmal_navn: "Ramsgjeltinden",
    telltur_turmaal_id: "myghxi9g_8076",
    _editable: false,
  },
  {
    id: 9575,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8080,
    turmal_type: "Fottur",
    turmal_navn: "Seglfjellet",
    telltur_turmaal_id: "myghxi9g_8080",
    _editable: false,
  },
  {
    id: 9576,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8058,
    turmal_type: "Fottur",
    turmal_navn: "Ingeborgfossen",
    telltur_turmaal_id: "myghxi9g_8058",
    _editable: false,
  },
  {
    id: 9577,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8055,
    turmal_type: "Fottur",
    turmal_navn: "Solvågtinden",
    telltur_turmaal_id: "myghxi9g_8055",
    _editable: false,
  },
  {
    id: 9578,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 4804,
    turmal_type: "Fottur",
    turmal_navn: "Storflåget",
    telltur_turmaal_id: "myghxi9g_4804",
    _editable: false,
  },
  {
    id: 9579,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8056,
    turmal_type: "Fottur",
    turmal_navn: "Storjord",
    telltur_turmaal_id: "myghxi9g_8056",
    _editable: false,
  },
  {
    id: 9580,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5392,
    turmal_type: "Sykkeltur",
    turmal_navn: "Sykkelstien i Saltdal",
    telltur_turmaal_id: "9bufw4ai_5392",
    _editable: false,
  },
  {
    id: 9581,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 6199,
    turmal_type: "Fottur",
    turmal_navn: "Bodøsjøen og Bodøelv",
    telltur_turmaal_id: "myghxi9g_6199",
    _editable: false,
  },
  {
    id: 9582,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 7836,
    turmal_type: "Fottur",
    turmal_navn: "Kvarven",
    telltur_turmaal_id: "myghxi9g_7836",
    _editable: false,
  },
  {
    id: 9583,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8077,
    turmal_type: "Fottur",
    turmal_navn: "Per Karlsatinden",
    telltur_turmaal_id: "myghxi9g_8077",
    _editable: false,
  },
  {
    id: 9584,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 5271,
    turmal_type: "Fottur",
    turmal_navn: "Keiservarden",
    telltur_turmaal_id: "myghxi9g_5271",
    _editable: false,
  },
  {
    id: 9585,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8074,
    turmal_type: "Fottur",
    turmal_navn: "Mjelle",
    telltur_turmaal_id: "myghxi9g_8074",
    _editable: false,
  },
  {
    id: 9586,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8075,
    turmal_type: "Fottur",
    turmal_navn: "Saltstraumen",
    telltur_turmaal_id: "myghxi9g_8075",
    _editable: false,
  },
  {
    id: 9587,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8072,
    turmal_type: "Fottur",
    turmal_navn: "Rognlivatnet rundt",
    telltur_turmaal_id: "myghxi9g_8072",
    _editable: false,
  },
  {
    id: 9588,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8082,
    turmal_type: "Fottur",
    turmal_navn: "Finneidvarden",
    telltur_turmaal_id: "myghxi9g_8082",
    _editable: false,
  },
  {
    id: 9589,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8084,
    turmal_type: "Fottur",
    turmal_navn: "Sagmoen fra Jakobsbakken",
    telltur_turmaal_id: "myghxi9g_8084",
    _editable: false,
  },
  {
    id: 9590,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8020,
    turmal_type: "Fottur",
    turmal_navn: "Kvalhornet",
    telltur_turmaal_id: "myghxi9g_8020",
    _editable: false,
  },
  {
    id: 9591,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8021,
    turmal_type: "Fottur",
    turmal_navn: "Øvre Valnesfjord",
    telltur_turmaal_id: "myghxi9g_8021",
    _editable: false,
  },
  {
    id: 9592,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8821,
    turmal_type: "Fottur",
    turmal_navn: "Koppartoppen",
    telltur_turmaal_id: "myghxi9g_8821",
    _editable: false,
  },
  {
    id: 9593,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8083,
    turmal_type: "Nærtur",
    turmal_navn: "Sjønstå gård",
    telltur_turmaal_id: "gxaxz7hb_8083",
    _editable: false,
  },
  {
    id: 9594,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 4813,
    turmal_type: "Fottur",
    turmal_navn: "Straumklumpen",
    telltur_turmaal_id: "myghxi9g_4813",
    _editable: false,
  },
  {
    id: 9595,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8059,
    turmal_type: "Fottur",
    turmal_navn: "Gjerdalen",
    telltur_turmaal_id: "myghxi9g_8059",
    _editable: false,
  },
  {
    id: 9596,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8063,
    turmal_type: "Fottur",
    turmal_navn: "Rago",
    telltur_turmaal_id: "myghxi9g_8063",
    _editable: false,
  },
  {
    id: 9597,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8060,
    turmal_type: "Fottur",
    turmal_navn: "Sørfjorddalen",
    telltur_turmaal_id: "myghxi9g_8060",
    _editable: false,
  },
  {
    id: 9598,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8051,
    turmal_type: "Fottur",
    turmal_navn: "Mørsvikvasstinden",
    telltur_turmaal_id: "myghxi9g_8051",
    _editable: false,
  },
  {
    id: 9599,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8049,
    turmal_type: "Fottur",
    turmal_navn: "Brennviksanden",
    telltur_turmaal_id: "myghxi9g_8049",
    _editable: false,
  },
  {
    id: 9600,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8048,
    turmal_type: "Fottur",
    turmal_navn: "Bøsanden",
    telltur_turmaal_id: "myghxi9g_8048",
    _editable: false,
  },
  {
    id: 9601,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8050,
    turmal_type: "Fottur",
    turmal_navn: "Skarbua",
    telltur_turmaal_id: "myghxi9g_8050",
    _editable: false,
  },
  {
    id: 9602,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 4966,
    turmal_type: "Fottur",
    turmal_navn: "Sørskottinden",
    telltur_turmaal_id: "myghxi9g_4966",
    _editable: false,
  },
  {
    id: 9603,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8047,
    turmal_type: "Fottur",
    turmal_navn: "Trohornet",
    telltur_turmaal_id: "myghxi9g_8047",
    _editable: false,
  },
  {
    id: 9604,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 7918,
    turmal_type: "Fottur",
    turmal_navn: "Glimma rundt",
    telltur_turmaal_id: "myghxi9g_7918",
    _editable: false,
  },
  {
    id: 9605,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8027,
    turmal_type: "Fottur",
    turmal_navn: "Hatten",
    telltur_turmaal_id: "myghxi9g_8027",
    _editable: false,
  },
  {
    id: 9606,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8024,
    turmal_type: "Fottur",
    turmal_navn: "Skaftheia/Hamarøyskaftet",
    telltur_turmaal_id: "myghxi9g_8024",
    _editable: false,
  },
  {
    id: 9607,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8000,
    turmal_type: "Fottur",
    turmal_navn: "Straumstien på Ness",
    telltur_turmaal_id: "myghxi9g_8000",
    _editable: false,
  },
  {
    id: 9608,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8819,
    turmal_type: "Fottur",
    turmal_navn: "Hellmobotn",
    telltur_turmaal_id: "myghxi9g_8819",
    _editable: false,
  },
  {
    id: 9609,
    points: 1,
    fk_telltur_konkurranse: 424,
    turmal_id: 8045,
    turmal_type: "Fottur",
    turmal_navn: "Jensvasskollen på Ulvsvågskaret",
    telltur_turmaal_id: "myghxi9g_8045",
    _editable: false,
  },
];
